#!/usr/bin/env python

import re
import sys

bit_re = re.compile("^\s*([0-9]+|\*)\s+(.*)$")

def row(cells, tot):
    # cells will have a list of (size, name) tuples that add to 32 or more bits, 
    # unless it is the last line
    elip = ""
    rowbits = sum([int(s) for s,n in cells if s != '*'])
    if rowbits == 0:
        rowbits = 32
        elip = "<br />..."

    if tot == '*':
        print """    <tr>
        <th class='code'>*<br />...</th>
        <th class='code'>*<br />...</th>"""
    else:
        print """    <tr>
        <th class='code'>%d%s</th>
        <th class='code'>%d%s</th>""" % (tot/8, elip, tot, elip)
        
    for sz, name in cells:
        if sz == '*':
            if not name:
                name = "&nbsp;"
            print "        <td colspan='32'>%s<br />...</td>" % (name,)
            tot = '*'
            rowbits -= 32
        else:
            isz = int(sz)
            if isz == 1:
                name = '<br />'.join(list(name))
                print "        <td>%s</td>" % (name,)
                rowbits -= 1
            elif isz > 32:
                if not name:
                    name = "&nbsp;"
                print "        <td rowspan='%d' colspan='32'>%s</td>" % (isz/32, name)
                rowbits -= 32
            else:
                if not name:
                    name = "&nbsp;"
                print "        <td colspan='%s'>%s</td>" % (sz, name)
                rowbits -= isz
            tot += isz
    print "    </tr>"
    while rowbits > 0:
        print """    <tr>
        <th class='pdu-offset'>%d%s</th>
        <th class='pdu-offset'>%d%s</th>
    </tr>""" % (tot/8, elip, tot, elip)
        rowbits -= 32
        tot += 32
    return tot

for fn in sys.argv[1:]:
    f = open(fn)
    print """
<!DOCTYPE html>
<html>
<head>
<title>%s</title>
<link rel="stylesheet" type="text/css" href="styles.css">
</head>
<body>
<table class='pdu'>
  <tbody>
    <tr>
        <th class='pdu-offsets'>Offsets</th>
        <th class='pdu-octet-row'>Octet</th>
        <th class='code' colspan="8">0</th>
        <th class='code' colspan="8">1</th>
        <th class='code' colspan="8">2</th>
        <th class='code' colspan="8">3</th>
    </tr>
    <tr class='pdu-bits'>
        <th class='pdu-octet-col'>Octet</th>
        <th>Bit</th>
        <th class='code'>&#xA0;0</th><th class='code'>&#xA0;1</th><th class='code'>&#xA0;2</th><th class='code'>&#xA0;3</th>
        <th class='code'>&#xA0;4</th><th class='code'>&#xA0;5</th><th class='code'>&#xA0;6</th><th class='code'>&#xA0;7</th>
        <th class='code'>&#xA0;8</th><th class='code'>&#xA0;9</th><th class='code'>10</th><th class='code'>11</th>
        <th class='code'>12</th><th class='code'>13</th><th class='code'>14</th><th class='code'>15</th>
        <th class='code'>16</th><th class='code'>17</th><th class='code'>18</th><th class='code'>19</th>
        <th class='code'>20</th><th class='code'>21</th><th class='code'>22</th><th class='code'>23</th>
        <th class='code'>24</th><th class='code'>25</th><th class='code'>26</th><th class='code'>27</th>
        <th class='code'>28</th><th class='code'>29</th><th class='code'>30</th><th class='code'>31</th>
    </tr>""" % (fn,)

    tot = 0
    rowbits = 0
    nextrow = []
    for ln in f.readlines():
        m = bit_re.search(ln)
        if not m: continue

        (sz, name) = m.groups()
        nextrow.append((sz, name))
        if sz == '*':
            tot = row(nextrow, tot)
            nextrow = []
            rowbits = 0
        else:
             rowbits += int(sz)
             if rowbits >= 32:
                tot = row(nextrow, tot)
                nextrow = []
                rowbits = 0

    if nextrow:
        tot = row(nextrow, tot)
            
    print """
  </tbody>
</table>
</body>
</html>"""
    f.close()
